Create webhook recurrence
mundipagg/ecommerce-module-core pull request #104
Opened 2019-11-21 16:00 UTC by wallaceSF

| Questions     | Answers
| ------------- | -------------------------------------------------------
| **Issue**         | https://mundipagg.atlassian.net/browse/MOD-855
| **What?**         | Creating webhook to recurrence

2019-11-21 18:13 UTC, michelpl requested changes

2019-11-21 18:13 UTC, michelpl commented on src/Recurrence/Aggregates/Invoice.php
> +
Remover linha extra

2019-11-21 18:13 UTC, michelpl commented on src/Recurrence/Factories/ChargeFactory.php
> +        $charge = new Charge();
Vamos diminuir o número de responsabilidades desse método criando métodos menores.

2019-11-21 18:13 UTC, michelpl commented on src/Recurrence/Factories/ChargeFactory.php
> +        $charge = new Charge();
Mesma coisa para os métodos seguintes.

2019-11-21 18:13 UTC, michelpl commented on src/Recurrence/Factories/ChargeFactory.php
> +    private function treatCardData(array $tranCardData, $index)
Remover tipagem por incompatibilidade com PHP 5.6

2019-11-21 18:13 UTC, michelpl commented on src/Recurrence/Factories/ChargeFactory.php
> +    private function treatBoletoUrl(array $tranBoletoUrl, $index)
Remover tipagem por incompatibilidade com PHP 5.6

2019-11-21 18:13 UTC, michelpl commented on src/Recurrence/Factories/InvoiceFactory.php
> +
Remover linha extra

2019-11-21 18:13 UTC, michelpl commented on src/Webhook/Services/SubscriptionHandlerService.php
> +
Remover linha extra

2019-11-21 18:13 UTC, michelpl commented on src/Webhook/Services/SubscriptionHandlerService.php
> +        $outdatedSubscription = $subscriptionRepository->findByMundipaggId($subscription->getMundipaggId());
Quebrar essa linha para não exceder os 80 caracteres

2019-11-21 18:13 UTC, michelpl commented on src/Webhook/Services/SubscriptionHandlerService.php
> +        $subscriptionRepository = new \Mundipagg\Core\Recurrence\Repositories\SubscriptionRepository();
Importar classe através do use

2019-11-21 18:13 UTC, michelpl commented on src/Webhook/Services/SubscriptionHandlerService.php
> +       // $order = $orderRepository->findByMundipaggId($order->getMundipaggId());
Remover código comentado

2019-11-21 18:16 UTC, michelpl requested changes

2019-11-21 18:16 UTC, michelpl commented on src/Kernel/Services/APIService.php
> +            $subscriptionData = $subscriptionController->getSubscription($subscriptionId->getValue());
Quebrar linha para respeitar os 80 caracteres

2019-11-21 18:16 UTC, michelpl commented on src/Recurrence/Factories/SubscriptionFactory.php
> +        $subscription->setIntervalType(IntervalValueObject::{$postData['interval']}($postData['interval_count']));
Quebrar linha para respeitar os 80 caracteres

2019-11-21 18:16 UTC, michelpl commented on src/Recurrence/Factories/SubscriptionFactory.php
> +        $subscription->setIntervalType(IntervalValueObject::{$dbData['interval_type']}($dbData['interval_count']));
Quebrar linha para respeitar os 80 caracteres

2019-11-21 18:16 UTC, michelpl commented on src/Webhook/Aggregates/Webhook.php
> +        if ((isset($data['invoice']) && !empty($data['invoice'])) || $this->type->getEntityType() == 'subscription') {
Quebrar linha para respeitar os 80 caracteres

2019-11-21 23:10 UTC, GabrielDeveloper commented on src/Webhook/Services/ChargeRecurrenceService.php
> +        //provalvemente tirar isso
Se puder testa um webhook sem esta linha para poder tirar o comentario e o comando updateCharge

2019-11-21 23:11 UTC, GabrielDeveloper commented on src/Webhook/Services/ChargeRecurrenceService.php
> +        //provalvement tirar isso
o mesmo que no metodo handlePaid

2019-11-21 23:16 UTC, GabrielDeveloper commented on src/Webhook/Services/ChargeOrderService.php
> +
retirar linha vazia

2019-11-21 23:16 UTC, GabrielDeveloper commented on src/Webhook/Services/ChargeRecurrenceService.php
> +
retirar linha vazia

2019-11-21 23:17 UTC, GabrielDeveloper commented on src/Webhook/Services/ChargeRecurrenceService.php
> +
retirar linha vazia

2019-11-24 13:52 UTC, wallaceSF commented on src/Recurrence/Factories/ChargeFactory.php
> +    private function treatCardData(array $tranCardData, $index)
Desde o PHP 5.1 existe typehint de array

2019-11-24 13:53 UTC, wallaceSF commented on src/Recurrence/Factories/ChargeFactory.php
> +    private function treatBoletoUrl(array $tranBoletoUrl, $index)
Desde 5.1 existe typehint de array

2019-11-26 14:03 UTC, merged