Feature mod 857 create cart conflict recurrence
mundipagg/ecommerce-module-core pull request #109
Opened 2019-12-07 15:30 UTC by wallaceSF

| Questions     | Answers
| ------------- | -------------------------------------------------------
| **Issue**         | https://mundipagg.atlassian.net/browse/MOD-857
| **What?**         |Create rules to conflict checkout in each aggregates that will call.

2019-12-09 15:11 UTC, GabrielDeveloper requested changes

2019-12-09 15:11 UTC, GabrielDeveloper commented on src/Recurrence/Repositories/SubProductRepository.php
> +    //tirei tipagem
Retirar comentario

2019-12-09 15:11 UTC, GabrielDeveloper commented on src/Recurrence/Repositories/ProductSubscriptionRepository.php
> -    public function findByProductId($productId)
Porque deletou esse método? esta sendo usado em varias classes

2019-12-09 15:11 UTC, GabrielDeveloper commented on src/Recurrence/Services/RulesCheckout.php
> +class RulesCheckout
Temos por uma convenção (acho que própria rs) colocar o prefixo "Service" nas classes dos serviços. Favor renomear

2019-12-11 14:57 UTC, michelpl requested changes

2019-12-11 14:57 UTC, michelpl commented on src/Recurrence/Aggregates/ProductSubscription.php
> +    public function checkProductHasSameMethodPayment(ProductSubscription $productSubscription)
Mudar de MethodPayment para PaymentMethod no nome do método e também nas variáveis.
Verificar na chamada do método para não quebrar.

2019-12-11 16:11 UTC, merged