Create subscription at Mundipagg
mundipagg/ecommerce-module-core pull request #119
Opened 2019-12-30 23:19 UTC by michelpl

| Questions     | Answers
| ------------- | -------------------------------------------------------
| **Issue**         | https://mundipagg.atlassian.net/browse/MOD-858
| **What?**         | Create subscription at Mundipagg
| **Why?**          | Create subscription products

2019-12-31 13:05 UTC, wallaceSF submitted a review, later dismissed

2019-12-31 13:08 UTC, wallaceSF reviewed
Dê uma olhada no teste, não passou

2020-01-02 15:04 UTC, GabrielDeveloper requested changes

2020-01-02 15:04 UTC, GabrielDeveloper commented on src/Kernel/I18N/ENUS.php
> +            'weekly' => null,
Retirar valor duplicado de 'weekly'

2020-01-02 15:04 UTC, GabrielDeveloper commented on src/Kernel/I18N/PTBR.php
> +            'weekly' => 'Semanal',
Retirar valor duplicado de 'weekly'

2020-01-02 15:04 UTC, GabrielDeveloper commented on src/Recurrence/Services/ResponseHandlers/SubscriptionHandler.php
> +use Mundipagg\Core\Kernel\ValueObjects\OrderStatus as OrderStatus;
Retirar alias, pois é o mesmo nome da classe

2020-01-02 15:04 UTC, GabrielDeveloper commented on tests/Recurrence/Factories/PlanTests.php
> +        $plan = $planFactory->createFromDbData("");
Retirar essa linha pois o plano é criado na linha 107 com os dados de $data, acho que essa linha era de um teste antigo onde não tínhamos implementado totalmente o método createFromDbData()

2020-01-02 18:07 UTC, GabrielDeveloper approved these changes

2020-01-02 18:32 UTC, merged