Cancel multi method charge
mundipagg/ecommerce-module-core pull request #142
Opened 2020-02-03 22:48 UTC by wallaceSF

| Questions     | Answers
| ------------- | -------------------------------------------------------
| **Issue**         | https://mundipagg.atlassian.net/browse/MOD-930
| **What?**         | Create structure to cancel charge paid (multimethod when exist paid between failed.)
| **Why?**          | Because an charge stay pay in mundipagg

2020-02-03 22:50 UTC, wallaceSF commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 6
           

Coverage decreased per file
===========================
- src/Kernel/Aggregates/Charge.php  -1
         

Clones added
============
- src/Webhook/Services/ChargeOrderService.php  1
- src/Kernel/Services/ChargeService.php  2
- src/Webhook/Services/ChargeRecurrenceService.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/mundipagg/ecommerce-module-core/pullRequest?prid=4938457&bid=16329075)

2020-02-04 15:36 UTC, michelpl requested changes

2020-02-04 15:36 UTC, michelpl commented on src/Webhook/Services/ChargeHandlerService.php
> +        $multiMeiosCanceled = $this->tryCancelMultiMethods($webhook);
Traduzir variável

2020-02-04 15:36 UTC, michelpl commented on src/Webhook/Services/ChargeHandlerService.php
> +            $multiMeiosCanceled
Traduzir variável

2020-02-04 15:36 UTC, michelpl commented on src/Webhook/Services/ChargeOrderService.php
> +            "message" => $returnMessage . '  '. $response,
Adicionar espaço entre aspas e ponto

2020-02-04 15:40 UTC, GabrielDeveloper approved these changes

2020-02-04 15:40 UTC, GabrielDeveloper commented on src/Webhook/Services/ChargeHandlerService.php
> +        $multiMeiosCanceled = $this->tryCancelMultiMethods($webhook);
Trocar multimeios para multimethods

2020-02-04 15:40 UTC, GabrielDeveloper commented on src/Webhook/Services/ChargeHandlerService.php
> +            $multiMeiosCanceled
Trocar multimeios para multimethods

2020-02-04 16:01 UTC, wallaceSF commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 6
           

Coverage decreased per file
===========================
- src/Kernel/Aggregates/Charge.php  -1
         

Clones added
============
- src/Webhook/Services/ChargeRecurrenceService.php  1
- src/Kernel/Services/ChargeService.php  2
- src/Webhook/Services/ChargeOrderService.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/mundipagg/ecommerce-module-core/pullRequest?prid=4938457&bid=16329075)

2020-02-04 17:44 UTC, wallaceSF commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 6
           

Clones added
============
- src/Kernel/Services/ChargeService.php  2
- src/Webhook/Services/ChargeOrderService.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/mundipagg/ecommerce-module-core/pullRequest?prid=4938457&bid=16329075)

2020-02-04 17:45 UTC, merged