Refactoring recurrence configurations
mundipagg/ecommerce-module-core pull request #145
Opened 2020-02-11 17:14 UTC by GabrielDeveloper

| Questions     | Answers
| ------------- | -------------------------------------------------------
| **Issue**         | https://mundipagg.atlassian.net/browse/MOD-933
| **What?**         | Refactoring recurrence configurations
| **Why?**          | To allow the cart conflicts configuration
| **How?**          | Changing the recurrence config object and added more configurations

2020-02-11 17:33 UTC, wallaceSF commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 9
- Added 4
           

Coverage decreased per file
===========================
- src/Kernel/Factories/RecurrenceConfigFactory.php  -12
- src/Kernel/ValueObjects/Configuration/RecurrenceConfig.php  -24
         

Complexity increasing per file
==============================
- src/Kernel/Factories/RecurrenceConfigFactory.php  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/mundipagg/ecommerce-module-core/pullRequest?prid=4985325&bid=16461689)

2020-02-11 18:50 UTC, wallaceSF commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 9
- Added 11
           

Complexity increasing per file
==============================
- src/Recurrence/Services/Rules/CompatibleRecurrenceProducts.php  3
- src/Recurrence/Services/Rules/ProductListInCart.php  1
- src/Recurrence/Services/Rules/NormalWithRecurrenceProduct.php  3
- src/Kernel/Factories/RecurrenceConfigFactory.php  3
- src/Recurrence/Services/Rules/MoreThanOneRecurrenceProduct.php  2
- src/Recurrence/Services/Rules/CurrentProduct.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/mundipagg/ecommerce-module-core/pullRequest?prid=4985325&bid=16461689)

2020-02-11 21:40 UTC, wallaceSF commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 9
- Added 16
           

Complexity increasing per file
==============================
- tests/Recurrence/Services/Rules/ProductListInCartTest.php  1
- tests/Recurrence/Services/Rules/CompatibleRecurrenceProductsTest.php  1
- src/Recurrence/Services/Rules/MoreThanOneRecurrenceProduct.php  2
- src/Recurrence/Services/Rules/CompatibleRecurrenceProducts.php  3
- tests/Recurrence/Services/Rules/CurrentProductTest.php  1
- src/Recurrence/Services/Rules/CurrentProduct.php  1
- tests/Recurrence/Services/Rules/NormalWithRecurrenceProductTest.php  2
- src/Recurrence/Services/Rules/NormalWithRecurrenceProduct.php  3
- src/Recurrence/Services/Rules/ProductListInCart.php  1
- tests/Recurrence/Services/Rules/MoreThanOneRecurrenceProductTest.php  2
- src/Kernel/Factories/RecurrenceConfigFactory.php  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/mundipagg/ecommerce-module-core/pullRequest?prid=4985325&bid=16461689)

2020-02-12 14:08 UTC, wallaceSF commented on src/Recurrence/Services/Rules/NormalWithRecurrenceProduct.php
> +    public function setError($error)
Esse método está como público. Pode mudar para uma classe abstrata sem corpo protected ou remover esse contrato dá interface.

2020-02-12 15:37 UTC, michelpl requested changes

2020-02-12 15:37 UTC, michelpl commented on src/Kernel/I18N/PTBR.php
> +            'The recurrence products should have the same payment configuration and the same interval' => 'Os produtos recorrentes devem ter a mesma configuração de pagamento e intervalo',
Só um comentário: O cliente final não sabe o que é um produto recorrente, então quando formos colocar mais mensagens desse tipo, pensar em algo que o cliente entenda.

2020-02-12 15:37 UTC, michelpl commented on src/Recurrence/Services/Rules/CompatibleRecurrenceProducts.php
> +
Trocar o nome da pasta Rules pra CartRules

2020-02-13 00:47 UTC, wallaceSF commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 9
- Added 16
           

Complexity increasing per file
==============================
- tests/Recurrence/Services/CartRules/CurrentProductTest.php  1
- src/Recurrence/Services/CartRules/CurrentProduct.php  1
- src/Recurrence/Services/CartRules/ProductListInCart.php  1
- tests/Recurrence/Services/CartRules/CompatibleRecurrenceProductsTest.php  1
- tests/Recurrence/Services/CartRules/ProductListInCartTest.php  1
- tests/Recurrence/Services/CartRules/NormalWithRecurrenceProductTest.php  2
- src/Kernel/Factories/RecurrenceConfigFactory.php  3
- tests/Recurrence/Services/CartRules/MoreThanOneRecurrenceProductTest.php  2
- src/Recurrence/Services/CartRules/MoreThanOneRecurrenceProduct.php  2
- src/Recurrence/Services/CartRules/CompatibleRecurrenceProducts.php  3
- src/Recurrence/Services/CartRules/NormalWithRecurrenceProduct.php  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/mundipagg/ecommerce-module-core/pullRequest?prid=4985325&bid=16461689)

2020-02-13 15:14 UTC, wallaceSF commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 9
- Added 16
           

Complexity increasing per file
==============================
- src/Recurrence/Services/CartRules/CompatibleRecurrenceProducts.php  3
- tests/Recurrence/Services/CartRules/CompatibleRecurrenceProductsTest.php  1
- src/Recurrence/Services/CartRules/ProductListInCart.php  1
- tests/Recurrence/Services/CartRules/CurrentProductTest.php  1
- tests/Recurrence/Services/CartRules/MoreThanOneRecurrenceProductTest.php  2
- src/Recurrence/Services/CartRules/MoreThanOneRecurrenceProduct.php  2
- tests/Recurrence/Services/CartRules/ProductListInCartTest.php  1
- src/Recurrence/Services/CartRules/CurrentProduct.php  1
- src/Recurrence/Services/CartRules/NormalWithRecurrenceProduct.php  3
- src/Kernel/Factories/RecurrenceConfigFactory.php  3
- tests/Recurrence/Services/CartRules/NormalWithRecurrenceProductTest.php  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/mundipagg/ecommerce-module-core/pullRequest?prid=4985325&bid=16461689)

2020-02-13 18:29 UTC, michelpl approved these changes

2020-02-13 18:45 UTC, wallaceSF approved these changes

2020-02-13 18:48 UTC, merged