Payment data details
mundipagg/ecommerce-module-core pull request #159
Opened 2020-03-24 14:18 UTC by wallaceSF

| Questions     | Answers
| ------------- | -------------------------------------------------------
| **Issue**         | https://mundipagg.atlassian.net/browse/MOD-979
| **What?**         | Now we saved the transaction object in the column transaction data
| **Why?**          | It was necessary for the customer

2020-03-24 14:35 UTC, michelpl requested changes

2020-03-24 14:35 UTC, michelpl commented on src/Kernel/Factories/ChargeFactory.php
> +    private function treatTranData(array $tranData, $index)
Temos que evitar abreviações. Para não mudar o código todo, muda no escopo dessa função e o nome dela para handleTransactionData

2020-03-24 14:50 UTC, GabrielDeveloper approved these changes

2020-03-24 18:10 UTC, wallaceSF commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/mundipagg/ecommerce-module-core/pullRequest?prid=5237038&bid=17165867)

2020-03-24 21:40 UTC, wallaceSF commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Clones added
============
- src/Kernel/Factories/ChargeFactory.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/mundipagg/ecommerce-module-core/pullRequest?prid=5237038&bid=17165867)

2020-03-24 22:07 UTC, wallaceSF commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/mundipagg/ecommerce-module-core/pullRequest?prid=5237038&bid=17165867)

2020-03-24 22:11 UTC, wallaceSF commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/mundipagg/ecommerce-module-core/pullRequest?prid=5237038&bid=17165867)

2020-03-24 22:27 UTC, michelpl approved these changes

2020-03-24 22:27 UTC, michelpl commented on src/Kernel/Factories/ChargeFactory.php
>              foreach ($tranId as $index => $id) {
Vendo o arquivo inteiro, dá pra ver que esse foreach tá gigante já. Extrai ele pra um novo método

2020-03-24 22:28 UTC, wallaceSF commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/mundipagg/ecommerce-module-core/pullRequest?prid=5237038&bid=17165867)

2020-03-27 16:03 UTC, wallaceSF commented on src/Kernel/Factories/ChargeFactory.php
>              foreach ($tranId as $index => $id) {
Não tem como separar sem deixar mais complexo ainda o método, já que eu seria obrigado a passar todos esses itens como parâmetro.

2020-03-27 16:04 UTC, merged