Sanitize json configuration
mundipagg/ecommerce-module-core pull request #180
Opened 2020-07-22 02:10 UTC by wallaceSF

| Questions     | Answers
| ------------- | -------------------------------------------------------
| **Issue**         | https://mundipagg.atlassian.net/browse/CONECT-1104
| **What?**         | Does sanitize JSON when it comes with special characters
| **Why?**          | because the JSON broken

2020-07-22 02:11 UTC, wallaceSF commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ src/Kernel/Repositories/ConfigurationRepository.php  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/mundipagg/ecommerce-module-core/pullRequest?prid=5891213&bid=19288428)

2020-07-22 02:20 UTC, GabrielDeveloper approved these changes

2020-07-24 17:04 UTC, michelpl requested changes

2020-07-24 17:04 UTC, michelpl commented on src/Kernel/Repositories/ConfigurationRepository.php
> +                '/\\\s+\\\s\\\r\\\n|\\\r|\\\n\\\r|\\\n/m',
Coloca esse regex numa variável

2020-07-24 17:04 UTC, michelpl commented on src/Kernel/Repositories/ConfigurationRepository.php
> +        $jsonEncoded = trim(
Código duplicado pode ser extraído para um outro método

2020-07-24 19:28 UTC, michelpl requested changes

2020-07-24 19:28 UTC, michelpl commented on src/Kernel/Repositories/ConfigurationRepository.php
> +    private function treatJsonString($jsonEncoded)
O método pode se chamar removeSpecialCharacters

2020-07-24 20:01 UTC, merged