Resilience
mundipagg/ecommerce-module-core pull request #188
Opened 2020-07-29 22:24 UTC by wallaceSF

| Questions     | Answers
| ------------- | -------------------------------------------------------
| **Issue**         | https://mundipagg.atlassian.net/browse/CONECT-1099
| **What?**         | Implements resiliency when creating the order
| **Why?**          | Helps to get around when the API is unstable, example when creating an order creating on one side only of the process

2020-07-29 22:26 UTC, wallaceSF commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- src/Kernel/Services/OrderResilienceService.php  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/mundipagg/ecommerce-module-core/pullRequest?prid=5931769&bid=19435276)

2020-08-13 21:12 UTC, michelpl requested changes

2020-08-13 21:12 UTC, michelpl commented on src/Kernel/Services/OrderResilienceService.php
> +        $resilience = false;
Mudar para success

2020-08-13 21:12 UTC, michelpl commented on src/Kernel/Services/OrderResilienceService.php
> +    private function checkRunResilience(\Exception $exception)
checkHttpStatusCode

2020-08-13 21:12 UTC, michelpl commented on src/Kernel/Services/OrderResilienceService.php
> +        $resilience = false;
Mudar para $retry

2020-08-13 21:12 UTC, michelpl commented on src/Kernel/Services/OrderResilienceService.php
> +class OrderResilienceService
Mudar para OrderCreationService

2020-08-13 21:12 UTC, michelpl commented on src/Kernel/Services/OrderResilienceService.php
> +        if ($resilience && $times > 1) {
Caso seja possível manter a recursividade, extrair para um método chamado orderRetry

2020-08-13 21:12 UTC, michelpl commented on src/Kernel/Services/OrderResilienceService.php
> +    public function createOrderResilience(
Mudar para OrderCreation

2020-11-09 15:25 UTC, GabrielDeveloper requested changes

2020-11-09 15:25 UTC, GabrielDeveloper commented on src/Kernel/Services/APIService.php
> +                $this->uuidv4(),
Essse aqui é o Idempotency? Acho que cairá no mesmo caso do woocomerce, gerando um idempotency randômico para cada pedido.

Acho melhor ou adicionarmos a mesma regra ou ficar sem mesmo.

2020-11-24 14:12 UTC, GabrielDeveloper submitted a review, later dismissed

2020-11-24 18:40 UTC, michelpl requested changes

2020-11-24 18:40 UTC, michelpl commented on src/Kernel/Services/OrderCreationService.php
> +<?php
"Resilience" não faz muito sentido no contexto do código. Trocar tudo que for **resilience** por **retry**

2020-11-24 18:40 UTC, michelpl commented on src/Kernel/Services/OrderCreationService.php
> +    private function checkRunResilience(Exception $exception)
Trocar nome do método para isSuccess()

2020-11-24 18:40 UTC, michelpl commented on src/Kernel/Services/OrderCreationService.php
> +        $resilience = false;
trocar para $success

2020-11-24 18:40 UTC, michelpl commented on src/Kernel/Services/OrderCreationService.php
> +        $resilience = false;
trocar para $success

2020-11-24 18:40 UTC, michelpl commented on src/Kernel/Services/OrderCreationService.php
> +            $resilience = $this->checkRunResilience($exception);
$success =

2020-11-24 18:40 UTC, michelpl commented on src/Kernel/Services/OrderCreationService.php
> +        $retry = 1
Trocar $retry por $attempts

2020-11-24 18:40 UTC, michelpl commented on src/Kernel/Services/OrderCreationService.php
> +        if ($resilience && $retry > 1) {
if (!$success && $attempts > 1)

2020-11-24 18:40 UTC, michelpl commented on src/Kernel/Services/OrderCreationService.php
> +            $currentTime = ($retry - 1);
$currentAttempt

2020-11-24 18:40 UTC, michelpl commented on src/Kernel/Services/OrderCreationService.php
> +                $currentTime
$currentAttempt

2020-11-24 18:40 UTC, michelpl commented on src/Kernel/Services/OrderCreationService.php
> +}
Faltou checar se o pedido foi realmente criado ou não. Acontece muitas vezes de dar timeout na requisição, mas o pedido criar na mundi depois de alguns segundos. Nesse caso, o pedido iria ficar duplicado,
Antes de cada retentativa, é necessário dar um get na api pra ver se isso não aconteceu

2020-11-24 18:43 UTC, wallaceSF commented on src/Kernel/Services/OrderCreationService.php
> +    private function checkRunResilience(Exception $exception)
O metodo não checa se é sucesso, mas sim se está nos padrões para rodar novamente

2020-12-04 16:50 UTC, michelpl approved these changes

2020-12-04 16:50 UTC, michelpl commented on src/Kernel/Services/OrderCreationService.php
> +    private function checkRunResilience(Exception $exception)
Então muda shouldRetry

2020-12-04 16:50 UTC, michelpl commented on src/Kernel/Services/OrderCreationService.php
> +        $resilience = false;
$shouldRetry = false

2021-01-15 15:37 UTC, merged