[Feature] Magento Pix
mundipagg/ecommerce-module-core pull request #202
Opened 2020-11-16 18:56 UTC by GabrielDeveloper

| Questions     | Answers
| ------------- | -------------------------------------------------------
| **Issue**         | https://mundipagg.atlassian.net/browse/CONNECT-1215
| **What?**         | Creates pix checkout for Magento 2

2020-11-17 15:22 UTC, michelpl requested changes

2020-11-17 15:22 UTC, michelpl commented on src/Payment/Services/OrderService.php
> +                if (!empty($data['qr_code']) && !empty($data['qr_code_url'])) {
Três níveis de identação

2020-11-19 14:12 UTC, wallaceSF submitted a review, later dismissed

2020-11-19 14:12 UTC, wallaceSF commented on src/Kernel/ValueObjects/PaymentMethod.php
> +    static public function pix()
muda para public static function

2020-11-19 14:12 UTC, wallaceSF commented on src/Payment/Aggregates/Payments/PixPayment.php
> +use Mundipagg\Core\Kernel\Abstractions\AbstractEntity;
Provavelmente essas classes não estão sendo utilizadas

2020-11-19 14:12 UTC, wallaceSF commented on src/Payment/Aggregates/Payments/PixPayment.php
> +use Mundipagg\Core\Kernel\Abstractions\AbstractEntity;
use Mundipagg\Core\Kernel\Abstractions\AbstractEntity;
use Mundipagg\Core\Kernel\Exceptions\InvalidParamException;
use Mundipagg\Core\Payment\Aggregates\Customer;
use Mundipagg\Core\Payment\ValueObjects\AbstractCardIdentifier;
use Mundipagg\Core\Payment\ValueObjects\PixBank;
use MundiAPILib\Models\CreateBoletoPaymentRequest;

2020-11-19 14:12 UTC, wallaceSF commented on src/Payment/Aggregates/Payments/PixPayment.php
> +    static public function getBaseCode()
public static funcion

2020-11-19 14:12 UTC, wallaceSF commented on src/Payment/ValueObjects/PaymentMethod.php
> +    {
public static funcion

2020-11-19 14:12 UTC, wallaceSF commented on src/Payment/ValueObjects/PixBank.php
> +    /**
static function nesse arquivo

2020-11-19 14:12 UTC, wallaceSF commented on src/Payment/Factories/PaymentFactory.php
> +    private function createPixPayments($data)
fala no doc block o que ele esta retornando

2020-11-19 14:12 UTC, wallaceSF commented on src/Payment/Factories/PaymentFactory.php
> +    private function createPixPayments($data)
/**
     * @param array $data
     * @return PixPayment[]
     * @throws InvalidParamException
     */

exemplo

2020-11-19 14:22 UTC, merged