[Enhancement] Only handle charge Webhook's
mundipagg/ecommerce-module-core pull request #209
Opened 2021-01-25 19:23 UTC by wallaceSF

| Questions     | Answers
| ------------- | -------------------------------------------------------
| **Issue**         | https://mundipagg.atlassian.net/browse/PAA-157
| **What?**         |Now the webhook's charges are responsible for changing the order status and creating invoices.
| **Why?**          | Was having a lot of synchronization problems between the order and charge webhook
| **How?**          | The order handle is now called together with the charge handle

2021-01-25 19:35 UTC, pedrolucasmr commented
Tem que ver esses problemas que apareceram aí.

2021-01-25 21:40 UTC, nmaia submitted a review, later dismissed

2021-01-25 23:43 UTC, GabrielDeveloper requested changes

2021-01-25 23:43 UTC, GabrielDeveloper commented on src/Kernel/Aggregates/Order.php
> +        $chargesStatusEquals = false;
Acho que pode mudar para $chargesStatusEquals = count($listChargeStatus) == 1;

2021-01-25 23:43 UTC, GabrielDeveloper commented on src/Kernel/Aggregates/Order.php
> +            $this->setStatus(OrderStatus::paid());
[Duvida] Quando temos um cenário de 2 charges pagas, ele faz o setStatus pra paid aqui em outro lugar?

2021-01-26 14:03 UTC, wallaceSF commented on src/Kernel/Aggregates/Order.php
> +        $chargesStatusEquals = false;
Boa. Feito!

2021-01-26 14:03 UTC, wallaceSF commented on src/Kernel/Aggregates/Order.php
> +            $this->setStatus(OrderStatus::paid());
no último if

2021-01-26 14:03 UTC, wallaceSF commented on src/Kernel/Aggregates/Order.php
> +            $this->setStatus(OrderStatus::paid());
if (
            $chargesStatusEquals &&
            !$this->getCharges()[0]->getStatus()->equals(ChargeStatus::underpaid())
        ) {
            $currentStatus = reset($listChargeStatus);
            $this->setStatus(OrderStatus::$currentStatus());
        }

2021-01-26 14:34 UTC, GabrielDeveloper approved these changes, later dismissed

2021-01-26 15:19 UTC, nmaia approved these changes, later dismissed

2021-01-27 20:23 UTC, nmaia approved these changes, later dismissed

2021-02-09 21:51 UTC, GabrielDeveloper approved these changes

2021-02-09 21:53 UTC, merged

2021-02-09 21:55 UTC, michelpl approved these changes