Cancels all charges if one of them fail in an order
mundipagg/ecommerce-module-core pull request #215
Opened 2021-03-25 18:09 UTC by netorodrigues

| Questions     | Answers
| ------------- | -------------------------------------------------------
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-68
| **What?**         | Makes core imediatelly request the cancelation of all charges in a multimeans order if one of the charge fails.

#### :package: Attachments (if appropriate)
Add additional informations like screenshots, issue link, etc

#### :speech_balloon: Important guidelines

* Add pull request labels.
* Check base branch.
* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!

2021-03-26 14:48 UTC, michelpl requested changes

2021-03-26 14:48 UTC, michelpl commented on src/Kernel/Services/OrderService.php
> +    public function cancelChargesAtMundipagg(Order $order){
Jogar chave pra linha de baixo

2021-03-26 14:48 UTC, michelpl commented on src/Kernel/Services/OrderService.php
> +                $charge->getStatus()->equals(ChargeStatus::failed()) ){
Quebrar linha e acertar espaçamento
```
if (
    $charge->getStatus()->equals(ChargeStatus::canceled()) ||
    $charge->getStatus()->equals(ChargeStatus::failed())
){
```

2021-03-30 20:59 UTC, willian-soaresferreira submitted a review, later dismissed

2021-03-30 21:05 UTC, michelpl submitted a review, later dismissed

2021-03-30 22:41 UTC, willian-soaresferreira submitted a review, later dismissed

2021-03-30 22:46 UTC, willian-soaresferreira approved these changes

2021-03-30 22:59 UTC, merged