Sanitize customer document
mundipagg/ecommerce-module-core pull request #221
Opened 2021-07-30 19:39 UTC by yanpantoja

| Questions     | Answers
| ------------- | -------------------------------------------------------
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-185
| **What?**         | Sanitize customer document to fix invalid request
| **Why?**          | Because the invalid request caused an error when editing a customer or update the credit to the customer's account

2021-07-30 19:59 UTC, vberardi approved these changes, later dismissed

2021-07-30 22:01 UTC, willian-soaresferreira approved these changes

2021-07-30 22:02 UTC, willian-soaresferreira requested changes
O código tá ok mano :) mas precisa resolver o problema do Codeclimate que está sendo mostrado nos checks.

2021-07-30 22:41 UTC, netorodrigues approved these changes

2021-07-31 00:59 UTC, willian-soaresferreira approved these changes

2021-08-02 17:48 UTC, merged