Feature/mod 640 save card n boleto
mundipagg/ecommerce-module-core pull request #30
Opened 2019-03-25 21:04 UTC by ianlessa

| Questions     | Answers
| ------------- | -------------------------------------------------------
| **Issue**         | https://mundipagg.atlassian.net/browse/MOD-640
| **What?**         | Add Boleto Payment method and saved credit cards.

2019-03-26 13:55 UTC, GabrielDeveloper requested changes

2019-03-26 13:55 UTC, GabrielDeveloper commented on src/Payment/Aggregates/Customer.php
> +
retirar linha em branco

2019-03-26 13:55 UTC, GabrielDeveloper commented on src/Payment/Repositories/SavedCardRepository.php
> +        if ($object->getOwnerId() === null)
abrir chaves na mesma linha do if

2019-03-27 18:13 UTC, michelpl approved these changes

2019-03-27 18:13 UTC, michelpl commented on src/Payment/Repositories/SavedCardRepository.php
> +            You can\'t save a card withou an onwer!' , null
Faltou o 't' no without

2019-03-27 18:19 UTC, merged