Create Recurrence Config Value Object and add on configuration
mundipagg/ecommerce-module-core pull request #40
Opened 2019-04-08 14:33 UTC by GabrielDeveloper

| Questions     | Answers
| ------------- | -------------------------------------------------------
| **Issue**         | https://mundipagg.atlassian.net/browse/MOD-
| **What?**         | Create Recurrence Config Value Object and add on configuration
| **Why?**          | To have the recurrence configuration on core configurations
| **How?**          | Create an object of recurrence configuration and add on core configurations

2019-04-08 17:26 UTC, LilianaLessa requested changes

2019-04-08 17:26 UTC, ianlessa commented on src/Kernel/Aggregates/Configuration.php
> +    /** @var Recurrence */
Nome de classe pode ser mais expressivo, algo como RecurrenceConfig

2019-04-08 17:26 UTC, ianlessa commented on src/Kernel/ValueObjects/Configuration/Recurrence.php
> +final class Recurrence extends AbstractValueObject
Nome da classe deveria ser mais semântico, algo como RecurrenceConfig

2019-04-08 17:26 UTC, ianlessa commented on src/Kernel/ValueObjects/Configuration/Recurrence.php
> +    public function setPlanSubscription($planSubscription)
Pra respeitar a invariabilidade de um value object, todos os setters devem ser privados.

2019-04-08 19:58 UTC, LilianaLessa submitted a review, later dismissed

2019-04-08 20:12 UTC, LilianaLessa submitted a review, later dismissed

2019-04-10 14:28 UTC, michelpl approved these changes

2019-04-10 20:45 UTC, LilianaLessa approved these changes

2019-04-10 20:45 UTC, merged