Partial capture fixes
mundipagg/ecommerce-module-core pull request #53
Opened 2019-05-07 20:34 UTC by ianlessa

| Questions     | Answers
| ------------- | -------------------------------------------------------
| **Issue**         | https://mundipagg.atlassian.net/browse/MOD-668
| **What?**         | Partial capture fixes
| **Why?**          | Partial capture webhook handling was broken.

2019-05-07 20:45 UTC, GabrielDeveloper requested changes

2019-05-07 20:45 UTC, GabrielDeveloper commented on src/Webhook/Services/OrderHandlerService.php
> +                [ChargeStatus::PENDING, ChargeStatus::PROCESSING]
Acho que ficou estranho essa identação, nao cabe jogar esse array de status numa variável ai ficaria 
if (in_array($chargeStatus, $statusAvailable)) ou algo assim??

2019-05-07 21:50 UTC, michelpl approved these changes

2019-05-08 13:42 UTC, GabrielDeveloper approved these changes

2019-05-08 18:12 UTC, merged