Unit tests module core
mundipagg/ecommerce-module-core pull request #94
Opened 2019-10-03 21:07 UTC by wallaceSF

| Questions     | Answers
| ------------- | -------------------------------------------------------
| **What?**         | Creating DockerFile and unifying branchs, change code to psr 1 and 2
| **Why?**          | Start to use an pattern in code. Avoid commit to production without testing before
| **How?**          | Created another branch with this features

2019-10-03 21:40 UTC, GabrielDeveloper requested changes

2019-10-03 21:40 UTC, GabrielDeveloper commented on README.md
> +# E-commerce Module Core
Copiar o Readme e substituir, pois este README era o antigo e acabou apagando as novas info

2019-10-03 21:40 UTC, GabrielDeveloper commented on src/Kernel/Aggregates/Charge.php
> +                $transaction = $updatedTransaction; // neste momento ele esta atualizando toda a transaction pois está sendo passada por referencia
Retirar comentario, isso era uma duvida e vamos ver melhor quando voltarmos a testar este metodo

2019-10-03 21:40 UTC, GabrielDeveloper commented on src/Kernel/ValueObjects/Installment.php
> +    public function __construct(int $times, int $baseTotal, float $interest)
Retirar essas tipagens pois só são compativeis com versão do php maior que 7.0

2019-10-03 22:19 UTC, michelpl requested changes

2019-10-03 22:19 UTC, michelpl commented on Dockerfile
> +RUN docker-php-ext-install mysqli pdo pdo_mysql pdo_pgsql zip
Retirar

2019-10-03 22:19 UTC, michelpl commented on composer.json
> +  "version": "1.7.2",
Compatibilizar com versão 5.6

2019-10-03 22:19 UTC, michelpl commented on tests/Kernel/ValueObjects/CardBrandTest.php
> +
Retirar linha extra

2019-10-03 22:19 UTC, michelpl commented on tests/Kernel/ValueObjects/InstallmentTest.php
> +
Retirar linha extra

2019-10-07 14:52 UTC, GabrielDeveloper commented on src/Kernel/ValueObjects/Installment.php
> +    public function __construct(int $times, int $baseTotal, float $interest)
Fazer esta mudança no branch de compatibilização com versão 5.6

2019-10-07 14:52 UTC, GabrielDeveloper commented on composer.json
> +  "version": "1.7.2",
Fazer esta mudança no branch de compatibilização com versão 5.6

2019-10-07 15:17 UTC, GabrielDeveloper submitted a review, later dismissed

2019-10-07 19:12 UTC, michelpl submitted a review, later dismissed

2019-10-07 19:42 UTC, michelpl approved these changes

2019-10-08 14:29 UTC, GabrielDeveloper approved these changes

2019-10-08 14:30 UTC, merged